8.0 return correct return code, no tee, fixes #24

diff --git a/travis/travis_run_tests b/travis/travis_run_tests
--- a/travis/travis_run_tests
+++ b/travis/travis_run_tests
@@ -68,12 +68,20 @@ command="$server_path/openerp-server -d ${database} ${options} \
 
 echo
 echo ${command}
-coverage run $command | tee stdout.log
 
-if $(grep -v mail stdout.log | egrep -q "(At least one test failed when loading the modules.|ERROR ${database})")
-then
-    exit 1
-else
-    exit 0
-fi
+case ${version} in 
+    5.0|6.0|6.1|7.0)
+        coverage run $command | tee stdout.log
 
+        if $(grep -v mail stdout.log | egrep -q "(At least one test failed when loading the modules.|ERROR ${database})")
+        then
+            exit 1
+        else
+            exit 0
+        fi
+        ;;
+    *)
+        coverage run $command
+        exit $?
+        ;;
+esac
