[REF] travis_install_nightly: Exit if clone_oca_depedencies script returned different to zero

diff --git a/travis/travis_install_nightly b/travis/travis_install_nightly
--- a/travis/travis_install_nightly
+++ b/travis/travis_install_nightly
@@ -82,6 +82,11 @@ fi
 
 echo "Getting addons dependencies"
 clone_oca_dependencies ${HOME} ${TRAVIS_BUILD_DIR}/..
+clone_result=$?
+if [ clone_result != 0  ]; then
+    echo "Error cloning dependencies"
+    exit clone_result
+fi;
 
 # Install web ribbon
 git clone --single-branch --depth=1 https://github.com/OCA/web.git -b ${VERSION} ${HOME}/web-environment-ribbon-isolated \
